@token = Bearer im_a_valid_user

### create cluster
POST http://localhost:8080/v1/cluster HTTP/1.1
Content-Type: application/json
Authorization: {{token}}

{    
    "id": "356e42a8-e659-406f-98bb-6124414675e8",
    "name": "cluster_1"
}

### update cluster
PUT http://localhost:8080/v1/cluster HTTP/1.1
Content-Type: application/json
Authorization: {{token}}

{    
    "id": "356e42a8-e659-406f-98bb-6124414675e8",
    "name": "cluster_2"
}


### get clusters
GET http://localhost:8080/v1/cluster HTTP/1.1
Authorization: {{token}}

### get cluster
GET http://localhost:8080/v1/cluster/356e42a8-e659-406f-98bb-6124414675e8 HTTP/1.1
Authorization: {{token}}

### get bad cluster
GET http://localhost:8080/v1/cluster/356e42a8-e659-406f-98 HTTP/1.1
Authorization: {{token}}


### delete cluster
DELETE  http://localhost:8080/v1/cluster/356e42a8-e659-406f-98bb-6124414675e8 HTTP/1.1
Authorization: {{token}}
