[tasks.dev]
install_crate = "cargo-watch"
command = "cargo"
args = ["watch", "-x", "run"]

[tasks.dev-r]
install_crate = "cargo-watch"
command = "cargo"
args = ["watch", "-x", "run --release"]

[tasks.start]
command = "cargo"
args = ["run",  "--release"]

[tasks.db-init]
dependencies = ["db-start", "db-create", "db-migration-run"]

[tasks.db-start]
script_runner = "@shell"
script = '''
docker run -d --name cluster_node_api -p 1234:5432 -e POSTGRES_PASSWORD=postgres -e POSTGRES_USER=postgres -e POSTGRES_DB=cluster_node_api postgres
sleep 2
'''

[tasks.db-clear]
script_runner = "@shell"
script = '''
docker stop cluster_node_api
docker rm cluster_node_api
'''

[tasks.db-create]
install_crate = "sqlx-cli"
command = "sqlx"
args = ["database", "create"]

[tasks.db-migration-add]
install_crate = "sqlx-cli"
command = "sqlx"
args = ["migrate", "add", "${@}"]

[tasks.db-migration-run]
install_crate = "sqlx-cli"
command = "sqlx"
args = ["migrate", "run"]



[tasks.db-reset]
dependencies = ["db-clear", "db-init"]